export const GENERAL_ERROR = "GENERAL_ERROR";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const USER_DATA_START = "USER_DATA_START";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAIL = "USER_DATA_FAIL";

export const FIREBASE_STORY_IMAGE_UPLOADING_START = "FIREBASE_STORY_IMAGE_UPLOADING_START";
export const FIREBASE_STORY_IMAGE_UPLOADING_SUCCESS = "FIREBASE_STORY_IMAGE_UPLOADING_SUCCESS";
export const FIREBASE_STORY_IMAGE_UPLOADING_FAIL = "FIREBASE_STORY_IMAGE_UPLOADING_FAIL";

export const FIREBASE_STORY_UPLOAD_SUCCESS = "FIREBASE_STORY_UPLOAD_SUCCESS";